// <auto-generated />
using System;
using CyberSoc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberSoc.Api.Migrations
{
    [DbContext(typeof(CyberSocDbContext))]
    [Migration("20260910104045_InitialSocSchema")]
    partial class InitialSocSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DetectionSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("detection_source");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("MitreTechniqueId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mitre_technique_id");

                    b.Property<string>("MitreTechniqueName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mitre_technique_name");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("risk_score");

                    b.Property<Guid>("SecurityEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_event_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_alerts_incident_id");

                    b.HasIndex("SecurityEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_security_event_id");

                    b.HasIndex("EndpointId", "CreatedAtUtc")
                        .HasDatabaseName("ix_alerts_endpoint_id_created_at_utc");

                    b.HasIndex("SecurityEventId", "EndpointId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_security_event_id_endpoint_id");

                    b.HasIndex("Status", "Severity", "CreatedAtUtc")
                        .HasDatabaseName("ix_alerts_status_severity_created_at_utc");

                    b.ToTable("alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_alerts_risk_score", "risk_score >= 0 AND risk_score <= 100");
                        });
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Endpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operating_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_endpoints");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_endpoints_hostname");

                    b.HasIndex("Status", "LastSeenAtUtc")
                        .HasDatabaseName("ix_endpoints_status_last_seen_at_utc");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_incidents_assigned_user_id");

                    b.HasIndex("Status", "Severity", "CreatedAtUtc")
                        .HasDatabaseName("ix_incidents_status_severity_created_at_utc");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DestinationIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("destination_ip");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<DateTimeOffset>("EventTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("process_name");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("source_ip");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.HasAlternateKey("Id", "EndpointId")
                        .HasName("ak_security_events_id_endpoint_id");

                    b.HasIndex("EventTimestampUtc")
                        .HasDatabaseName("ix_security_events_event_timestamp_utc");

                    b.HasIndex("EndpointId", "EventTimestampUtc")
                        .HasDatabaseName("ix_security_events_endpoint_id_event_timestamp_utc");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("indicator_type");

                    b.Property<string>("IndicatorValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("indicator_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("ThreatName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("threat_name");

                    b.HasKey("Id")
                        .HasName("pk_threats");

                    b.HasIndex("IndicatorType", "IndicatorValue")
                        .HasDatabaseName("ix_threats_indicator_type_indicator_value");

                    b.HasIndex("IsActive", "LastSeenAtUtc")
                        .HasDatabaseName("ix_threats_is_active_last_seen_at_utc");

                    b.ToTable("threats", null, t =>
                        {
                            t.HasCheckConstraint("ck_threats_confidence_score", "confidence_score >= 0 AND confidence_score <= 100");
                        });
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_normalized", "email = upper(btrim(email)) AND length(email) > 0");
                        });
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Alert", b =>
                {
                    b.HasOne("CyberSoc.Api.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany("Alerts")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_endpoints_endpoint_id");

                    b.HasOne("CyberSoc.Api.Domain.Entities.Incident", "Incident")
                        .WithMany("Alerts")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_alerts_incidents_incident_id");

                    b.HasOne("CyberSoc.Api.Domain.Entities.SecurityEvent", "SecurityEvent")
                        .WithOne("Alert")
                        .HasForeignKey("CyberSoc.Api.Domain.Entities.Alert", "SecurityEventId", "EndpointId")
                        .HasPrincipalKey("CyberSoc.Api.Domain.Entities.SecurityEvent", "Id", "EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_security_events_security_event_id_endpoint_id");

                    b.Navigation("Endpoint");

                    b.Navigation("Incident");

                    b.Navigation("SecurityEvent");
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Incident", b =>
                {
                    b.HasOne("CyberSoc.Api.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incidents_users_assigned_user_id");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.SecurityEvent", b =>
                {
                    b.HasOne("CyberSoc.Api.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany("SecurityEvents")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_events_endpoints_endpoint_id");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Endpoint", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("SecurityEvents");
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("CyberSoc.Api.Domain.Entities.SecurityEvent", b =>
                {
                    b.Navigation("Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
